### ISSUE TITLE
ANZ NZ supports strong passwords

### ISSUE THREAD

**Issue by rafaelmagu** [ryankurte/doesmybank#6]
As per ANZ's own password change page:

![image](https://cloud.githubusercontent.com/assets/197444/20504966/2285d4ea-b0af-11e6-9b0f-3022c6474eb9.png)
The link on the screenshot goes to http://www.anz.co.nz/personal/ways-bank/protect-banking/banking-safely-online/

It has been tested to support upper and lowercase letters, numbers **and special characters**.

The 16-char limit seems to only apply to ANZ Australia.

**Comment by ryankurte** [comment]
Whoops, commit message should say ANZ.
Thanks @rafaelmagu!
